class ViolationCategory:
    VIOLATION_CATEGORY_JAVASCRIPT_SCHEME: int = 1
    VIOLATION_CATEGORY_INNER_OUTER_HTML: int = 2
    VIOLATION_CATEGORY_DOCUMENT_WRITE: int = 3
    VIOLATION_CATEGORY_EVAL: int = 4
    VIOLATION_CATEGORY_FUNCTION_CONSTRUCTOR: int = 5
    VIOLATION_CATEGORY_STYLE_ATTRIBUTE: int = 6